### ISSUE TITLE
Maintain Design Links Page

### ISSUE THREAD

**Issue by andyl** [bugmark/exchange#31]
I've got so many emails with links to Google Docs that I've lost 'situational awareness'.

I need a single wiki page with:
- our immediate next step - with links to the support docs
- links to all of our historical docs, for reference

Designers: please when you send out a link to a google doc, also add a link to that doc on this wiki page.

https://github.com/mvscorg/bugmark/wiki/Design-Links

Let me know if you have trouble updating this page, or if you want to maintain the page in a separate location.

Yes, we'll make this tradable soon!  Love that dogfood.  :-)

**Comment by guerillagirl** [comment]
Today is sketching day (yay!).

- Please spend no longer than one hour on your lofi sketches. 
- Sketching in teams is encouraged. 

- Example of what we will be expecting as lofi: [https://drive.google.com/file/d/0B69ZYdrCrLuCRmctanMydnlLLTA/view]

- Please upload your sketches here: [https://drive.google.com/drive/folders/0B69ZYdrCrLuCLXRCT1ZiLWRtV1k]


**Next steps**: 

- We will discuss the results of today's sketching on Wednesday.
