### ISSUE TITLE
J J Demo: missing 10 tokens

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/exchange#67]
Don ran the J J Demo at FOSDEM. Jane put up 10 token earnest money for a 100 token valued contract. After the contract was resolved, she only had 80 tokens more (instead of 90, that Joe put up).

I have not tried replicating this yet, but I have the impression having seen this discrpency before.

![image](https://user-images.githubusercontent.com/8862021/35777384-42f099ce-09ad-11e8-9f4c-6c9a69d50704.png)

**Comment by GeorgLink** [comment]
In #68 I propose a different display that might make more sense to a user. I use the same values of the J J Demo in #68 to show the 10 token difference I noticed.

**Comment by andyl** [comment]
Closing old issue.
