### ISSUE TITLE
Add ledger page for accounts with chronological change to wallet and running balance

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/exchange#68]
I envision a table with a chronological account of events on the user's account. Similar to a bank statement. Important for trust could be a running balance.

Relates to #67 to show how the account should be effected by the J J Demo.

|DateTime|Event|Outflow|Inflow|Balance|
|---|---|---|---|---|
|2018-02-03 12:00:00|Starting Balance||1000|
|2018-02-03 18:35:01|Escrow for Buy Offer # 273|10| | 990|
|2018-02-03 18:37:58|Payout of Contract # 23| |100| 1090|

**Comment by andyl** [comment]
Moved to bugmark/test_bench#100
