### ISSUE TITLE
Change REPO to TRACKER

### ISSUE THREAD

**Issue by andyl** [bugmark/exchange#72]
Let's change the term REPO to TRACKER.

**Comment by GeorgLink** [comment]
+1 Yes, much more sensible.
​

**Comment by andyl** [comment]
Probably I'll make this change in the next day or two.  This change will touch everything: the Exchange, the API, UIs, bots, etc.  @GeorgLink  I've got regression tests for most everything except your server-side bots.  So the change would likely break your code.  Let me know if you have time-critical activities in the next few days.  If not I'll go ahead...

**Comment by GeorgLink** [comment]
Okay, can you hold off until we have Malvika's experiment in place and
working?

**Comment by andyl** [comment]
Will do.

**Comment by andyl** [comment]
I had to tweak the DB schema (to add `user.name` field) so took the opportunity to make this change.  REPO has been renamed to TRACKER.  Code affected: `exchange`, `bmx_api_ruby`, `bmx_cl_ruby`, `bmx_bots`, `test_bench`.  All affected code has been updated, all regression tests pass.

@GeorgLink if you run into problems with your server-side bots, the remedy turns out to be pretty simple:
- replace REPO -> TRACKER
- replace Repo -> Tracker
- replace repo -> tracker

You may need to recreate the DB schema on your server:
- cd src/exchange
- git pull
- killall ruby
- bundle exec rails db:drop db:create db:migrate
 
After that you should be back in business.

**Comment by GeorgLink** [comment]
Thanks for the info and detailed steps.
