### ISSUE TITLE
Use of branches in repo?

### ISSUE THREAD

**Issue by GeorgLink** [bugmark/exchange#84]
It appears that the `master` branch is ahead of the `dev` branch. This is not intuitive for me and I would like clarity of how branches are used in this repo?

I ask, because the pull request #82 is against the dev branch, but people will start with the master branch, and if there is no path from dev to master, then I'm confused. Also, if the dev branch is meant for development environment, why should it not have the latest version of features?

**Comment by andyl** [comment]
Sorry about that - I fell into bad habits - will return to our agreed workflow.
